0-Auth/0Auth

.gitignore
=> .gitignore: Add gitignore

convention.md
=> convention.md: Add commit convention

.github/PULL_REQUEST_TEMPLATE.md
- It closes #2 
- It adds the template for the pull requests.
=> PULL_REQUEST_TEMPLATE.md: Add PR template

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
- It closes #1 
- It adds issue templates for the bug report and the feature request.
=> .github: Add ISSUE_TEMPLATE directory

.gitignore, package.json, packages/client/package.json, packages/client/src/index.d.ts, packages/client/src/index.ts, packages/client/tsconfig.json, packages/message/package.json, packages/message/src/index.d.ts, packages/message/src/index.ts, packages/message/tsconfig.json, packages/server/package.json, packages/server/src/index.d.ts, packages/server/src/index.ts, packages/server/tsconfig.json, tsconfig.json
- Configure tsconfig and package.json settings and add index.ts.
- It Related to #12
=> Add basic file structure

packages/client/src/index.ts, packages/message/src/index.ts, packages/server/src/index.ts
=> Add function skeleton

packages/message/src/index.ts
=> Add key to Property type

.eslintrc.json, package.json
=> Add eslint to each package

.gitignore, .mocharc.js, nycrc.config.js, package.json, packages/client/package.json, packages/client/src/index.d.ts, packages/client/src/index.ts, packages/client/tsconfig.json, packages/message/src/index.d.ts, packages/message/tsconfig.json, packages/server/package.json, packages/server/src/index.d.ts, packages/server/src/index.ts, packages/server/test/auth.spec.ts, packages/server/tsconfig.json, tsconfig.json
Fixed the point that import did not work properly due to tsconfig
and apply mocha, chai and nyc for testing
- It closes #5
=> Apply testing framework

.eslintrc.json, .prettierrc, nycrc.config.js, package.json, packages/client/src/index.ts, packages/client/tsconfig.json, packages/message/src/index.ts, packages/message/tsconfig.json, packages/server/src/index.ts, packages/server/test/auth.spec.ts, packages/server/tsconfig.json, tsconfig.eslint.json, tsconfig.json
.eslintrc.json: fix project config
tsconfig.eslint.json: added
.prettierrc: added
others: formatted
- It closes #24 
=> Fix eslint parser error

.github/workflows/CI.yml
Since lint in CI must be added after the skeleton function is implemented, I don't close related issue.
- It Related to #6
=> CI.yml: Add github action setting

.eslintrc.json, package.json, packages/client/package.json, packages/client/src/index.ts, packages/client/src/utils.ts, packages/client/test/client.spec.ts, packages/server/src/index.ts, packages/server/src/utils.ts
Implement functions to store and read user information and
server's signature in localStorage.
- It closes #17
=> client: Implement storing in localStorage

packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
Implement authentication and verification functions to check values
used together at once
- It closes #16 
=> server: Add authentication using package mode

packages/client/src/index.ts, packages/client/src/utils.ts, packages/client/test/client.spec.ts, packages/message/package.json, packages/message/src/index.ts, packages/message/test/message.spec.ts, packages/server/package.json, packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
Implement a function that can hide the value by receiving the key of the
property that client want to hide and mapping it with a hash.
- It closes #28 
=> client: Implement hide property function

packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
=> server: Implement function to receive user info

packages/client/package.json, packages/client/src/index.ts, packages/client/src/utils.ts, packages/client/test/client.spec.ts
=> Apply Optional type

.gitignore, lerna.json, package.json, packages/client/package.json, packages/client/tsconfig.json, packages/message/package.json, packages/message/tsconfig.json, packages/server/package.json, packages/server/tsconfig.json, tsconfig.json
Add lerna and modify package.json and tsconfig.json
- It Fixes #46
=> Modify settings for npm publish

.gitignore, examples/server/package.json, examples/server/src/index.ts, examples/server/src/utils.ts, examples/server/test/example-data.json, examples/server/tsconfig.json
Add an example to book a movie
even if the server does not store user information.
- It closes #42
=> example: Add server example

packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
=> server: Implement get public key from secret key

packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
Implement function for use when server issues properties.
- It closes #50
=> server: Implement issuance function

packages/message/src/index.ts, packages/message/test/message.spec.ts, packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
=> message: move some functions to message package

packages/client/src/index.ts, packages/client/src/utils.ts, packages/client/test/client.spec.ts
=> client: Add key settings for storing data

.github/workflows/CI.yml, README.md, packages/message/src/index.ts, packages/server/src/utils.ts
=> Fix minor bugs

packages/server/src/index.ts, packages/server/test/auth.spec.ts
Implement the function to execute supplier
when the condition is satisfied.
- It closes #64
=> server: Implement supply function after validation

examples/client/yarn.lock
=> Fix dependency security for node-forge

.eslintrc.json, .prettierrc, package.json, packages/client/src/index.ts, packages/client/src/utils.ts, packages/client/test/client.spec.ts, packages/message/src/index.ts, packages/message/test/message.spec.ts, packages/server/src/index.ts, packages/server/src/utils.ts, packages/server/test/auth.spec.ts
- It closes #70 
- After changes in this PR.
=> Fix eslint errors

.github/workflows/CI.yml, README.md, package.json
=> Add lint to github action

examples/client/package.json, examples/client/yarn.lock
=> Fix bug for object-path

packages/client/test/client.spec.ts, packages/message/src/property/hashProperty.ts, packages/message/src/property/objectToProperty.ts, packages/message/src/property/propertyObject.ts, packages/message/src/type/index.ts, packages/message/src/type/stringToDataType.ts, packages/message/src/type/type.ts, packages/message/src/type/typeOfObject.ts, packages/message/src/type/typeOfProperty.ts, packages/message/src/utils/utf8ToBase64.ts, packages/message/test/message.spec.ts, packages/server/src/issuer/authProperty.ts, packages/server/src/type/index.ts, packages/server/src/verifier/verifyProperty.ts, packages/server/test/auth.spec.ts
Expanded to receive not only string type but also number, boolean,
and date types.
- It closes #67
=> Make property value accept types other than string
